export default {
  LIGHT_PRIMARY_MAIN: '#2f516d',
  LIGHT_SECONDARY_MAIN: '#899bb2',

  LIGHT_BACKGROUND: '#e1e1e1',
  LIGHT_CARD_BORDER: '#e1e1e1',
  LIGHT_BACKGROUND_PANEL: '#ffffff',
  LIGHT_FONT_PRIMARY: '#2f516d',
  LIGHT_FONT_SECONDARY: '#899bb2',
  LIGHT_CAROUSEL: '#444444',

  DARK_PRIMARY_MAIN: '#2f51ff',
  DARK_SECONDARY_MAIN: '#899bb2',

  DARK_BACKGROUND: '#000',
  DARK_CARD_BORDER: '#000',
  DARK_BACKGROUND_PANEL: '#000',
  DARK_FONT_PRIMARY: '#fff',
  DARK_FONT_SECONDARY: '#ffb',
  DARK_CAROUSEL: '#444444'
};
